# dataset
root: 'data/budjbim_area'
img_size: 256
img_norm: True

# train config
epoch: 100
patience: 100
batch: 64
num_workers: 8
lr: 0.00005
w_decay: 0.05
optim: 'adamw'
device: 'cuda'
weight_mode: 'supervised'

# model
arch: 'vit_small'
mhs_encoder: null
vat_encoder: null
patch_size: 16
feature_indices: 
- 1
- 4
- 7
- 10
feature_channels: null
path: 'save/supervised_vitsmall16_siamese/'
